<?php
/**
 * Home list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if($_productCollection->count()): ?>
<div class="block block-home productlist">
    <div class="block-title">
		<strong><span><?php echo $this->__('Popular Products') ?></span></strong>
	</div>
	<div class="block-content">
<?php $_collectionSize = $_productCollection->count() ?>
<?php $_columnCount = 4; ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(145) ?>" width="145" height="145" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php echo $this->getPriceHtml($_product, true, '-new') ?>
                <div class="clear"></div>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
                <div class="clear"></div>
                <!--<ul class="add-to-links">
                        <?php // if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php // echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php // echo $this->__('Add to Wishlist') ?></a></li>
                        <?php // endif; ?>
                        <?php // if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php // echo $_compareUrl ?>" class="link-compare"><?php // echo $this->__('Add to Compare') ?></a></li>
                        <?php // endif; ?>
                    </ul>-->
            </li>
        <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        </ul>
        <?php endif ?>
    <?php endforeach; ?>
	<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <script type="text/javascript">
			var grids = $$('.products-grid');
			grids.each(function(n){					
					var columns = n.select('li.item');					
					var max_height = 0;									
					columns.each(function(m){			
						//console.log(m.getHeight());											
						if( m.getHeight() >  max_height ){
							max_height = m.getHeight();
						}						
					});
					var boxes = n.select('li .product-box');
					columns.each(function(b){					
						b.setStyle({
							height: max_height - 50 + 'px'
						});					
					 });
				});	
		</script>
	</div>
</div>
<?php endif; ?>
