<?php
 /**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2012 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 3.2
 * @since        Class available since Release 1.0
 */
?>
<div class="shipping-address" id="gcheckout-shipping-address">
	<ul class="form-list">
		<?php if ($this->customerHasAddresses()): ?>
			<li>
				<label for="shipping-address-select"><?php echo $this->__('Select shipping') ?></label>
				<div class="input-box">
					<?php echo $this->getAddressesHtmlSelect('shipping') ?>
				</div>
			</li>
		<?php endif; ?>
		<li id="shipping-new-address-form">
			<fieldset>
				<ul>
					<li class="fields"><?php echo $this->getLayout()->createBlock('gomage_checkout/onepage_name')->setObject($this->getAddress())->setFieldIdFormat('shipping_%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?></li>
					<?php $this->getSortedFields();?>
				</ul>
			</fieldset>
		</li>
		<?php if ($this->isCustomerLoggedIn()):?>
		<li id="shipping_address_book" class="control" style="display:none">
			<input type="checkbox" name="shipping[save_in_address_book]" id="shipping_save_in_address_book" value="1" title="<?php echo  $this->__('Save in address book') ?>" class="checkbox" /><label for="shipping_save_in_address_book"><?php echo  $this->__('Save in address book') ?></label>
		</li>
		<?php endif; ?>
	</ul>
</div>
</div>