<?php
/**
 * Category Logo
 *
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $catCollection = $_product->getCategoryCollection();
	$categs = $catCollection->exportToArray();
	$categsToLinks = array();
	foreach($categs as $ind=>$cat){
		if($cat['entity_id'] == 81){
			$_cat = Mage::getModel('catalog/category')->load($cat['entity_id']);
			$imageUrl = $_cat->getThumbnail();
			$catName = $_cat->getName();
			$catUrl = $_cat->getUrl();
			if($imageUrl){
				echo '<div class="block cat-logo"><a href="' . $catUrl . '"><img src="' . Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/catalog/category/' . $imageUrl . '" alt="' . $catName . '" /></a></div>';
			}
			return;
		}
	}
?>