<?php
/**
 * Room Planner CTA
 *
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $catCollection = $_product->getCategoryCollection();
	# export this collection to array so we could iterate on it's elements
	$categs = $catCollection->exportToArray();
	$categsToLinks = array();
	foreach($categs as $ind=>$cat){
		if($cat['entity_id'] == 90){
			echo $this->getLayout()->createBlock('cms/block')->setBlockId('room_planner')->toHTML();
		}
	}
?>