<?php
 /**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2012 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 3.2
 * @since        Class available since Release 1.0
 */
 ?>

<div class="checkout-address" id="gcheckout-address">
	<div class="block-title">
		<div class="glc-col-left billing-address">
		<div class="step-number"><strong><span>1</span></strong></div>
			<h2 class="glc-title"><span><?php echo $this->__('Enter Your Billing address');?></span></h2>
		</div>
		<div class="glc-col-right shipping-address">
			<h2 class="glc-title"><span><?php echo $this->__('Shipping address');?></span></h2>
		</div>
	</div>
	<div class="glc-col">
 		<?php echo $this->getChildHtml('billing');?>

<?php if(!Mage::getSingleton('checkout/session')->getQuote()->isVirtual() && intval(Mage::getStoreConfig('gomage_checkout/general/different_shipping_enabled'))): echo $this->getChildHtml('shipping'); endif;?>
	</div>
</div>